# Generated by Django 6.0.4 on 2026-04-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, default='Имя', max_length=20)),
                ('l_name', models.CharField(blank=True, default='Фамилия', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('male', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не указан', 'Не указан')], default='Не указан', max_length=20)),
                ('goal', models.CharField(choices=[('Сброс', 'Сброс'), ('Поддержание', 'Поддержание'), ('Набор', 'Набор')], default='Поддержание', max_length=20)),
                ('activity', models.IntegerField(choices=[(1, 'Отсутствие тренировок'), (2, '1–3 тренировки в неделю'), (3, '3–5 тренировок в неделю'), (4, '6–7 тренировок в неделю'), (5, 'Профессиональный спорт')], default=2)),
                ('plusstatus', models.BooleanField(default=False)),
                ('height', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('dete_birth', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
