# Generated by Django 6.0.4 on 2026-05-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0002_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Врач', 'Врач'), ('Тренер', 'Тренер'), ('Другое', 'Другое')], default='Другое', max_length=10)),
                ('about', models.TextField(default='Специалист', max_length=150)),
                ('f_name', models.CharField(blank=True, default='Имя', max_length=20)),
                ('l_name', models.CharField(blank=True, default='Фамилия', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
