# Generated by Django 6.0.4 on 2026-05-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0003_specialist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
