# Generated by Django 6.0.4 on 2026-05-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0008_specialist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AddField(
            model_name='specialist',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='social_tg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='specialist',
            table='a_profile_specialist',
        ),
    ]
