# Generated by Django 6.0.4 on 2026-05-07 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0009_alter_specialist_options_specialist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
