# Generated by Django 6.0.4 on 2026-04-19 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('calories', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'a_main_product',
            },
        ),
    ]
