# Generated by Django 6.0.4 on 2026-05-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_specialist', '0002_alter_specialist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
